Ext.define('plat.model.sme.SMEIdentifieModel', {
	extend : 'Ext.data.Model',
	fields: [
		{name : 'id', type : 'Integer'},
		{name : 'applicationReport', type : 'String'},
		{name : 'copiesOfDocuments', type : 'String'},
		{name : 'socialSecurityDetails', type : 'String'},
		{name : 'copyOfTheAuditReport', type : 'String'},
		{name : 'otherSupportingDocuments', type : 'String'},
		{name : 'applicationUndertaking', type : 'String'},
		{name : 'tenderDocuments', type : 'String'},
		{name : 'enterpriseInformationTable', type : 'String'},
		{name : 'companyName', type : 'String'},
		{name : 'registerDate', type : 'String'},
		{name : 'companyAddress', type : 'String'},
		{name : 'postcode', type : 'String'},
		{name : 'trades', type : 'String'},
		{name : 'webSite', type : 'String'},
		{name : 'responsiblePerson', type : 'String'},
		{name : 'responsiblePosition', type : 'String'},
		{name : 'responsiblePhone', type : 'String'},
		{name : 'responsibleMobile', type : 'String'},
		{name : 'contactPserson', type : 'String'},
		{name : 'contactName', type : 'String'},
		{name : 'contactPosition', type : 'String'},
		{name : 'contactPhone', type : 'String'},
		{name : 'contactFax', type : 'String'},
		{name : 'contactMobile', type : 'String'},
		{name : 'contactEmail', type : 'String'},
		{name : 'otherContactPerson', type : 'String'},
		{name : 'mainBusinessProducts', type : 'String'},
		{name : 'qualification', type : 'String'},
		{name : 'scaleIntroduction', type : 'String'},
		{name : 'problem', type : 'String'},
		{name : 'documenType', type : 'String'},
		{name : 'rushDate', type : 'String'},
		{name : 'user.userName', type : 'String'},
		{name : 'user.id', type : 'Integer'},
		{name : 'applicationTime', type : 'String'},
		{name : 'manager.username', type : 'String'},
		{name : 'manager.id', type : 'Integer'},
		{name : 'approvedTime', type : 'String'},
		{name : 'approveStatus', type : 'Integer'},
		{name : 'approvedOpinion', type : 'String'},
		{name : 'modifyTime', type : 'String'}
	]
});
